package v1_alpha

// KeyboardEvent represents a keyboard key press or release.
type KeyboardEvent string

// LED (lock) key state events reuse KeyboardEvent for convenience.
type NumLockState KeyboardEvent
type CapslockState KeyboardEvent
type ScrollLockState KeyboardEvent

const (
	NumLockOn           NumLockState = "num-lock-on"
	NumLockOff                       = "num-lock-off"
	NumLockNotSupported              = "num-lock-not-supported"

	CapslockOn           CapslockState = "caps-lock-on"
	CapslockOff                        = "caps-lock-off"
	CapslockNotSupported               = "caps-lock-not-supported"

	ScrollLockOn           ScrollLockState = "scroll-lock-on"
	ScrollLockOff                          = "scroll-lock-off"
	ScrollLockNotSupported                 = "scroll-lock-not-supported"
)

// Keyboard key press / release events:
const (
	KeyPressA            KeyboardEvent = "key-press-a"
	KeyPressB            KeyboardEvent = "key-press-b"
	KeyPressC            KeyboardEvent = "key-press-c"
	KeyPressD            KeyboardEvent = "key-press-d"
	KeyPressE            KeyboardEvent = "key-press-e"
	KeyPressF            KeyboardEvent = "key-press-f"
	KeyPressG            KeyboardEvent = "key-press-g"
	KeyPressH            KeyboardEvent = "key-press-h"
	KeyPressI            KeyboardEvent = "key-press-i"
	KeyPressJ            KeyboardEvent = "key-press-j"
	KeyPressK            KeyboardEvent = "key-press-k"
	KeyPressL            KeyboardEvent = "key-press-l"
	KeyPressM            KeyboardEvent = "key-press-m"
	KeyPressN            KeyboardEvent = "key-press-n"
	KeyPressO            KeyboardEvent = "key-press-o"
	KeyPressP            KeyboardEvent = "key-press-p"
	KeyPressQ            KeyboardEvent = "key-press-q"
	KeyPressR            KeyboardEvent = "key-press-r"
	KeyPressS            KeyboardEvent = "key-press-s"
	KeyPressT            KeyboardEvent = "key-press-t"
	KeyPressU            KeyboardEvent = "key-press-u"
	KeyPressV            KeyboardEvent = "key-press-v"
	KeyPressW            KeyboardEvent = "key-press-w"
	KeyPressX            KeyboardEvent = "key-press-x"
	KeyPressY            KeyboardEvent = "key-press-y"
	KeyPressZ            KeyboardEvent = "key-press-z"
	KeyPress0            KeyboardEvent = "key-press-0"
	KeyPress1            KeyboardEvent = "key-press-1"
	KeyPress2            KeyboardEvent = "key-press-2"
	KeyPress3            KeyboardEvent = "key-press-3"
	KeyPress4            KeyboardEvent = "key-press-4"
	KeyPress5            KeyboardEvent = "key-press-5"
	KeyPress6            KeyboardEvent = "key-press-6"
	KeyPress7            KeyboardEvent = "key-press-7"
	KeyPress8            KeyboardEvent = "key-press-8"
	KeyPress9            KeyboardEvent = "key-press-9"
	KeyPressF1           KeyboardEvent = "key-press-f1"
	KeyPressF2           KeyboardEvent = "key-press-f2"
	KeyPressF3           KeyboardEvent = "key-press-f3"
	KeyPressF4           KeyboardEvent = "key-press-f4"
	KeyPressF5           KeyboardEvent = "key-press-f5"
	KeyPressF6           KeyboardEvent = "key-press-f6"
	KeyPressF7           KeyboardEvent = "key-press-f7"
	KeyPressF8           KeyboardEvent = "key-press-f8"
	KeyPressF9           KeyboardEvent = "key-press-f9"
	KeyPressF10          KeyboardEvent = "key-press-f10"
	KeyPressF11          KeyboardEvent = "key-press-f11"
	KeyPressF12          KeyboardEvent = "key-press-f12"
	KeyPressEnter        KeyboardEvent = "key-press-enter"
	KeyPressEscape       KeyboardEvent = "key-press-escape"
	KeyPressBackspace    KeyboardEvent = "key-press-backspace"
	KeyPressTab          KeyboardEvent = "key-press-tab"
	KeyPressSpace        KeyboardEvent = "key-press-space"
	KeyPressMinus        KeyboardEvent = "key-press-minus"
	KeyPressEqual        KeyboardEvent = "key-press-equal"
	KeyPressBacktick     KeyboardEvent = "key-press-backtick"
	KeyPressBracketLeft  KeyboardEvent = "key-press-bracket-left"
	KeyPressBracketRight KeyboardEvent = "key-press-bracket-right"
	KeyPressBackslash    KeyboardEvent = "key-press-backslash"
	KeyPressSemicolon    KeyboardEvent = "key-press-semicolon"
	KeyPressQuote        KeyboardEvent = "key-press-quote"
	KeyPressComma        KeyboardEvent = "key-press-comma"
	KeyPressPeriod       KeyboardEvent = "key-press-period"
	KeyPressSlash        KeyboardEvent = "key-press-slash"
	KeyPressInsert       KeyboardEvent = "key-press-insert"
	KeyPressDelete       KeyboardEvent = "key-press-delete"
	KeyPressHome         KeyboardEvent = "key-press-home"
	KeyPressEnd          KeyboardEvent = "key-press-end"
	KeyPressPageUp       KeyboardEvent = "key-press-page-up"
	KeyPressPageDown     KeyboardEvent = "key-press-page-down"
	KeyPressArrowUp      KeyboardEvent = "key-press-arrow-up"
	KeyPressArrowDown    KeyboardEvent = "key-press-arrow-down"
	KeyPressArrowLeft    KeyboardEvent = "key-press-arrow-left"
	KeyPressArrowRight   KeyboardEvent = "key-press-arrow-right"
	KeyPressPrintScreen  KeyboardEvent = "key-press-print-screen"
	KeyPressPause        KeyboardEvent = "key-press-pause"
	KeyPressShiftLeft    KeyboardEvent = "key-press-shift-left"
	KeyPressShiftRight   KeyboardEvent = "key-press-shift-right"
	KeyPressControlLeft  KeyboardEvent = "key-press-control-left"
	KeyPressControlRight KeyboardEvent = "key-press-control-right"
	KeyPressAltLeft      KeyboardEvent = "key-press-alt-left"
	KeyPressAltRight     KeyboardEvent = "key-press-alt-right"
	KeyPressMetaLeft     KeyboardEvent = "key-press-meta-left"
	KeyPressMetaRight    KeyboardEvent = "key-press-meta-right"

	KeyReleaseA            KeyboardEvent = "key-release-a"
	KeyReleaseB            KeyboardEvent = "key-release-b"
	KeyReleaseC            KeyboardEvent = "key-release-c"
	KeyReleaseD            KeyboardEvent = "key-release-d"
	KeyReleaseE            KeyboardEvent = "key-release-e"
	KeyReleaseF            KeyboardEvent = "key-release-f"
	KeyReleaseG            KeyboardEvent = "key-release-g"
	KeyReleaseH            KeyboardEvent = "key-release-h"
	KeyReleaseI            KeyboardEvent = "key-release-i"
	KeyReleaseJ            KeyboardEvent = "key-release-j"
	KeyReleaseK            KeyboardEvent = "key-release-k"
	KeyReleaseL            KeyboardEvent = "key-release-l"
	KeyReleaseM            KeyboardEvent = "key-release-m"
	KeyReleaseN            KeyboardEvent = "key-release-n"
	KeyReleaseO            KeyboardEvent = "key-release-o"
	KeyReleaseP            KeyboardEvent = "key-release-p"
	KeyReleaseQ            KeyboardEvent = "key-release-q"
	KeyReleaseR            KeyboardEvent = "key-release-r"
	KeyReleaseS            KeyboardEvent = "key-release-s"
	KeyReleaseT            KeyboardEvent = "key-release-t"
	KeyReleaseU            KeyboardEvent = "key-release-u"
	KeyReleaseV            KeyboardEvent = "key-release-v"
	KeyReleaseW            KeyboardEvent = "key-release-w"
	KeyReleaseX            KeyboardEvent = "key-release-x"
	KeyReleaseY            KeyboardEvent = "key-release-y"
	KeyReleaseZ            KeyboardEvent = "key-release-z"
	KeyRelease0            KeyboardEvent = "key-release-0"
	KeyRelease1            KeyboardEvent = "key-release-1"
	KeyRelease2            KeyboardEvent = "key-release-2"
	KeyRelease3            KeyboardEvent = "key-release-3"
	KeyRelease4            KeyboardEvent = "key-release-4"
	KeyRelease5            KeyboardEvent = "key-release-5"
	KeyRelease6            KeyboardEvent = "key-release-6"
	KeyRelease7            KeyboardEvent = "key-release-7"
	KeyRelease8            KeyboardEvent = "key-release-8"
	KeyRelease9            KeyboardEvent = "key-release-9"
	KeyReleaseF1           KeyboardEvent = "key-release-f1"
	KeyReleaseF2           KeyboardEvent = "key-release-f2"
	KeyReleaseF3           KeyboardEvent = "key-release-f3"
	KeyReleaseF4           KeyboardEvent = "key-release-f4"
	KeyReleaseF5           KeyboardEvent = "key-release-f5"
	KeyReleaseF6           KeyboardEvent = "key-release-f6"
	KeyReleaseF7           KeyboardEvent = "key-release-f7"
	KeyReleaseF8           KeyboardEvent = "key-release-f8"
	KeyReleaseF9           KeyboardEvent = "key-release-f9"
	KeyReleaseF10          KeyboardEvent = "key-release-f10"
	KeyReleaseF11          KeyboardEvent = "key-release-f11"
	KeyReleaseF12          KeyboardEvent = "key-release-f12"
	KeyReleaseEnter        KeyboardEvent = "key-release-enter"
	KeyReleaseEscape       KeyboardEvent = "key-release-escape"
	KeyReleaseBackspace    KeyboardEvent = "key-release-backspace"
	KeyReleaseTab          KeyboardEvent = "key-release-tab"
	KeyReleaseSpace        KeyboardEvent = "key-release-space"
	KeyReleaseMinus        KeyboardEvent = "key-release-minus"
	KeyReleaseEqual        KeyboardEvent = "key-release-equal"
	KeyReleaseBacktick     KeyboardEvent = "key-release-backtick"
	KeyReleaseBracketLeft  KeyboardEvent = "key-release-bracket-left"
	KeyReleaseBracketRight KeyboardEvent = "key-release-bracket-right"
	KeyReleaseBackslash    KeyboardEvent = "key-release-backslash"
	KeyReleaseSemicolon    KeyboardEvent = "key-release-semicolon"
	KeyReleaseQuote        KeyboardEvent = "key-release-quote"
	KeyReleaseComma        KeyboardEvent = "key-release-comma"
	KeyReleasePeriod       KeyboardEvent = "key-release-period"
	KeyReleaseSlash        KeyboardEvent = "key-release-slash"
	KeyReleaseInsert       KeyboardEvent = "key-release-insert"
	KeyReleaseDelete       KeyboardEvent = "key-release-delete"
	KeyReleaseHome         KeyboardEvent = "key-release-home"
	KeyReleaseEnd          KeyboardEvent = "key-release-end"
	KeyReleasePageUp       KeyboardEvent = "key-release-page-up"
	KeyReleasePageDown     KeyboardEvent = "key-release-page-down"
	KeyReleaseArrowUp      KeyboardEvent = "key-release-arrow-up"
	KeyReleaseArrowDown    KeyboardEvent = "key-release-arrow-down"
	KeyReleaseArrowLeft    KeyboardEvent = "key-release-arrow-left"
	KeyReleaseArrowRight   KeyboardEvent = "key-release-arrow-right"
	KeyReleasePrintScreen  KeyboardEvent = "key-release-print-screen"
	KeyReleasePause        KeyboardEvent = "key-release-pause"
	KeyReleaseShiftLeft    KeyboardEvent = "key-release-shift-left"
	KeyReleaseShiftRight   KeyboardEvent = "key-release-shift-right"
	KeyReleaseControlLeft  KeyboardEvent = "key-release-control-left"
	KeyReleaseControlRight KeyboardEvent = "key-release-control-right"
	KeyReleaseAltLeft      KeyboardEvent = "key-release-alt-left"
	KeyReleaseAltRight     KeyboardEvent = "key-release-alt-right"
	KeyReleaseMetaLeft     KeyboardEvent = "key-release-meta-left"
	KeyReleaseMetaRight    KeyboardEvent = "key-release-meta-right"
)
